project:
  type: website
  output-dir: docs

website:
  title: "Caitlin Swalec"
  navbar:
    left:
      - about.qmd
      - CV.qmd
      - experience.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    ###page-layout: full

editor: visual

