---
title: Experience and Skills
toc: false
---

I have over 10 years of experience working on climate change and energy, with the last 6 years focused on heavy industry decarbonization. I currently lead Global Energy Monitor's Heavy Industry Program, overseeing a global team working across the iron and steel, cement, chemicals, and raw materials sectors. 

Selected areas of expertise are highlighted below. See my [CV](Caitlin_Swalec_CV_01_22_2025.pdf) for my full professional and academic experience..


+--------------------------------+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ### *Leadership*               |       | Director of Global Energy Monitor's Heavy Industry Program, managing a global team and portfolio of research projects spanning multiple industrial sectors. Experience in strategy, supervision, hiring, project management, and mentoring more than ten staff ranging from entry-level researchers to PhD-level professionals at once.                                                                                                                                                                |
+--------------------------------+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ### *Communications & media*  |       | Regularly communicate complex technical topics to journalists and reporters from outlets including CNN, the Financial Times, DW, South China Morning Post, Fastmarkets, and Canary Media. Published in industry outlets including GreenBiz, RENEW-Industry, and Steel Times International.            |
+--------------------------------+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ### *Fundraising*              |       | Lead fundraising and grant management for GEM's Heavy Industry Program, securing more than $1.75 million annually for research initiatives, from dozens of funders including multi-year renewals.                                                                                                                                                                    |
+--------------------------------+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ### *Engineering*              |       | Training and professional experience in air quality control and permitting, offshore wind farm planning, and chemical and industrial plant design. This technical background informs my understanding of the practical challenges of deploying industrial decarbonization technologies.                                            |
+--------------------------------+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ### *Endurance*                |       | Outside of work, I am a trail runner and ocean swimmer. I've completed a 12-mile channel swim in the Pacific Ocean, run 50 miles across the Grand Canyon and back, raced outrigger canoes accross the Catalina and Santa Barbara Channels, and competed in multiple marathon and ultramarathon-distance trail races. |
+--------------------------------+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

+--------------------------------+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ### *Leadership*               |   | Experience as a supervisor, lead fundraiser and grant manager, hiring lead, project manager, and mentor for more than ten supervisees ranging from entry-level to PhD qualifications.                                                                                                                                                                    |
+--------------------------------+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ### *Communications and media* |   | Regular contact with and experience communicating complex technical topics to journalists and reporters from outlets including CNN, the Financial Times, DW, South China Morning Post, Fastmarkets, and Canary Media. Publications in industry newsletters and journals including GreenBiz, RENEW-Industry, and Steel Times International.               |
+--------------------------------+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ### *Fundraising*              |   | Pitched and secured over \$1.75 million USD annually in funding for research initiatives in GEM's Heavy Industry Program, including one to three year renewals from five funders.                                                                                                                                                                        |
+--------------------------------+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ### *Engineering*              |   | Training and professional experience in air quality control and permitting, offshore windfarm planning, and chemical and industrial plant design. Strong understanding and appreciation for the practical challenges and opportunities of engineering and design, especially for climate change technologies.                                            |
+--------------------------------+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ### *Endurance*                |   | Demonstrated resilience, persistence, and positivity in the face of difficult tasks, including a 12-mile channel swim in the Pacific Ocean, a 50 mile run back and forth across the Grand Canyon, multiple marathon and ultramarathon length running races, and daily efforts to document and hold accountable emissions from the heavy industry sector. |
+--------------------------------+---+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

