---
title: "Publications"
toc: false
---

My most recent professional publications are listed below. A complete list is available in my [CV](Caitlin_Swalec_CV_01_22_2025.pdf).

<div>

## Research

1.  Grigsby-Schulte, Fanwei Liu, Caitlin Swalec, Rolando Almada, Larkin Cleland, Charmaine Dalisay, Ziwei Zhang, and Jessie Zhi. [Pedal to the Metal 2026: The iron and steel industry’s coal lock-in crisis.](https://globalenergymonitor.org/research/pedal-metal-2026) Global Energy Monitor. May 2026.

2.  Grigsby-Schulte, Henna Khadeeja, Caitlin Swalec, Rolando Almada, Ziwei Zhang, and Jessie Zhi. [Pedal to the Metal 2025: Evaluating progress toward 2030 iron and steel decarbonization goals.](https://globalenergymonitor.org/research/pedal-metal-2025) Global Energy Monitor. May 2025.

3.  Khadeeja, Henna and Caitlin Swalec. [Why India’s ‘build now, decarbonize later’ approach to achieving a net-zero steel industry will fail.](https://globalenergymonitor.org/wp-content/uploads/2024/11/GEM-India-steel-brief-December-2024.pdf) Global Energy Monitor. December 11, 2024.

4.  Swalec, Caitlin and Eileen Torres. [A matter of transparency: 2024 insights on the steel industry’s evolving commitments to reach Net Zero by 2050.](https://globalenergymonitor.org/report/a-matter-of-transparency-2024-insights-on-the-steel-industrys-evolving-commitments-to-reach-net-zero-by-2050/) Global Energy Monitor and Leadership Group for Industry Transition. October 30, 2024.

5.  Clark, Gregor and Caitlin Swalec. [Forging a sustainable future: Brazil’s opportunity to lead in steel decarbonization.](https://globalenergymonitor.org/report/forging-a-sustainable-future-brazils-opportunity-to-lead-in-steel-decarbonization/?utm_source=Global+Energy+Monitor&utm_campaign=6c70e1abe4-EMAIL_CAMPAIGN_2024_06_24_09_44_COPY_01&utm_medium=email&utm_term=0_-a8962d5afc-%5BLIST_EMAIL_ID%5D) Global Energy Monitor. August 2024.

6.  Armbruster, Marie, Astrid Grigsby-Schulte, and Caitlin Swalec. [Pedal to the Metal 2024: Building momentum for iron and steel decarbonization.](https://globalenergymonitor.org/report/pedal-to-the-metal-2024/) Global Energy Monitor. July 2024.

7.  Swalec, Caitlin, Hanna Fralikhina, and Zhanaiym Kozybay. [Pressure on Russia to be greener.](https://issuu.com/quartzbusinessmedia/docs/steel_times_international_digital_june_2024) Steel Times International. June 2024.

8.  Swalec, Caitlin, Jessie Zhi, and Ziwei Zhang. [In China, a small boost to low-emissions steelmaking can mean big cuts to its carbon footprint.](https://globalenergymonitor.org/report/in-china-a-small-boost-to-low-emissions-steelmaking-can-mean-big-cuts-to-its-carbon-footprint/) Global Energy Monitor. March 2024.

9.  Swalec, Caitlin, Hanna Fralikhina, and Zhanaiym Kozybay. [Russia doubles down on coal-based steelmaking, even as opportunity grows for greener technology.](https://globalenergymonitor.org/report/russia-doubles-down-on-coal-based-steelmaking-even-as-opportunity-grows-for-greener-technology/) Global Energy Monitor. February 2024.

</div>

<div>

## Poetry

1. "Under the California Sun, All Roads Lead Away From Maine." [Santa Barbara Literary Journal](https://www.santabarbaraliteraryjournal.com/): Volume 14: Noleta Liminal, edited by Maryanne Knight. November 2026 (anticipated).

2. "Onrushing." [Like the Wind Running Magazine](https://www.likethewindmagazine.com/shop/issue-50-of-like-the-wind-running-magazine/): Issue 50. September 2026.

3. "World Makers." [Santa Barbara Literary Journal](https://www.santabarbaraliteraryjournal.com/): Volume 13: Mysterious Ways, edited by Maryanne Knight. May 2026.

4. "Tuesday Farmer's Market." [A Feast for Santa Barbara](https://gunpowderpress.com/shop/a-feast-for-santa-barbara/): Gunpowder Press, edited by David Starkey. March 2026.

5.  "A deep blue devotion." [Santa Barbara Literary Journal](https://www.santabarbaraliteraryjournal.com/): Volume 11: This Must Be The Place, edited by Maryanne Knight. November 2024.

</div>
